/** 首页 Banner 首图裁剪比例（宽:高） */
export const HOME_BANNER_COVER_WIDTH = 700;
export const HOME_BANNER_COVER_HEIGHT = 316;
export const HOME_BANNER_COVER_ASPECT = HOME_BANNER_COVER_WIDTH / HOME_BANNER_COVER_HEIGHT;

/** 导出 2 倍图，兼顾清晰度与体积 */
export const HOME_BANNER_COVER_OUTPUT_WIDTH = HOME_BANNER_COVER_WIDTH * 2;
export const HOME_BANNER_COVER_OUTPUT_HEIGHT = HOME_BANNER_COVER_HEIGHT * 2;
